# Gradle performance / UX
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
# NeoForge
neo_version=21.1.217
loader_version_range=[1,)
# Dependency modids / versions
fzzy_mod_id=fzzy_config
fzzy_version=0.7.5+1.21+neoforge
jei_version=19.27.0.336
# SolExtended (embedded companion mod)
solextended_mod_id=solextended
solextended_name=SolExtended
solextended_version=1.0.0
# PermanentFood
mod_id=permanentfood
mod_name=PermanentFood
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=net.purple.permfood
